# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(blank=True, max_length=35, unique=True)),
                ('filepath', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('i', 'image'), ('v', 'video')], max_length=10)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15, unique=True)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.User'),
        ),
        migrations.AddField(
            model_name='media',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='app.Hashtag'),
        ),
    ]
